Script started on 2020-06-13 23:54:50-06:00
]0;daniel.jin@csa2:~/355/assignment5daniel.jin@csa2:~/355/assignment5$ ./a.out 5
1	3	3	8	3	
9	8	4	2	4	
7	3	6	0	0	
6	8	0	7	5	
3	2	0	7	5	
Enter in 111 to quit
Enter a column number: 0

Table sorted by column 0:
1	3	3	8	3	
3	8	4	2	4	
6	3	6	0	0	
7	8	0	7	5	
9	2	0	7	5	
Enter a column number: 1

Table sorted by column 1:
1	2	3	8	3	
3	3	4	2	4	
6	3	6	0	0	
7	8	0	7	5	
9	8	0	7	5	
Enter a column number: 2

Table sorted by column 2:
1	2	0	8	3	
3	3	0	2	4	
6	3	3	0	0	
7	8	4	7	5	
9	8	6	7	5	
Enter a column number: 3

Table sorted by column 3:
1	2	0	0	3	
3	3	0	2	4	
6	3	3	7	0	
7	8	4	7	5	
9	8	6	8	5	
Enter a column number: 4

Table sorted by column 4:
1	2	0	0	0	
3	3	0	2	3	
6	3	3	7	4	
7	8	4	7	5	
9	8	6	8	5	
Enter a column number: 111
]0;daniel.jin@csa2:~/355/assignment5daniel.jin@csa2:~/355/assignment5$ exit
exit

Script done on 2020-06-13 23:55:05-06:00
